### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by ssoonmi** [bamorgan13/cha-aux#1]
How are you going to implement direct messaging?

### `channels`
- [x] index on `server_id` should not be unique because a server can have many channels

### `posts`
- [x] index on `author_id` and `channel_id` should not be unique because a `channel` can have many posts by the same author, and a `channel` can have many `posts`

### `reactions`
- [x] index on `user_id` should not be unique because a `user` can have many `reactions` to many different `posts`

**Comment by bamorgan13** [comment]
Direct messaging will be implemented as posts to a private server where the two users are the only members. A 'private' boolean has been added to the server schema. This boolean will also be used to hide servers in the browse and search features.

**Comment by ssoonmi** [comment]
On discord, private messaging looks like a server, and the dm's look like channels. Also, you need a join table between users and servers and between users and channels. Because a user can be subscribed to a server, but not necessarily all the channels in a server.

**Comment by ssoonmi** [comment]
`server_id` should not be `not null`

**Comment by bamorgan13** [comment]
I made several changes to the schema to account for these issues.

+ `userChannels` and `userServers` was replaced with a single `memberships` table with a polymorphic `joinable` relationship to connect `users`.
 + `server_id` is no longer `not null` in `channels` in order to account for direct messaging.
+ `reactions` has been broken apart into two tables: `reactions` and `user_reactions`.
  + `reactions` stores a name and an image stored with AWS.
  + `user_reactions` is a joins table connecting a `user` to a `post` and a `reaction`.
  + This relationship will allow for users to create new reactions as well as provides the ability to use images such as gifs instead of being limited to emojis.
